package fr.limsi.negotiate.restaurant;
import java.util.ArrayList;
import java.util.List;

import fr.limsi.negotiate.Criterion;
import fr.limsi.negotiate.Option;

public enum Restaurant implements Option {
	ARLECCHINO(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.DOWNTOWN),
	ANDIAMO_PIZZERIA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	ANGOLO_LITALIA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.EAST_SIDE),
	ANTEPRIMA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.WEST_SIDE),
	ARCADIUS_RISTORANTE(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	AU_SOLEIL_ITALIEN(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.DOWNTOWN),
	BAROCCO(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.NORTH_SIDE),
	BELITALIE(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.EAST_SIDE),
	BELLA_ITALIA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.WEST_SIDE),
	BELLA_NAPOLI(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	BUONA_PASTA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	CAFFE_DITALIA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	CAFFE_DI_PASTA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	CAPRI_PIZZA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	CASA_DA_VINCI(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	CASA_DEL_ZIO(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.DOWNTOWN),
	CASA_ITALIA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	CASA_ITALIANA(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.EAST_SIDE),
	CASA_PASTAS(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.WEST_SIDE),
	CHALET_DU_GRAND_ARC(Cuisine.ITALIAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	CIAO_PASTA(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.LIVELY, Location.DOWNTOWN),
	CORNER_PASTA(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.LIVELY, Location.NORTH_SIDE),
	COSTA_COSTA(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.LIVELY, Location.EAST_SIDE),
	CITE_ITALIE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.LIVELY, Location.WEST_SIDE),
	CROISSAN_ITALIEN(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	DEL_ARTE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.QUIET, Location.DOWNTOWN),
	DEL_GLADIATORE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.QUIET, Location.NORTH_SIDE),
	DELICES_DITALIE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.QUIET, Location.EAST_SIDE),
	DELIZIE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.QUIET, Location.WEST_SIDE),
	DELIZIE_DUGGIANO(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.QUIET, Location.SOUTH_SIDE),
	DINO_RISTORANTE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	DOLCE_ITALIA(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	DOLCE_PASTA(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	DOLCE_VITA(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	DON_CAMILLO(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	ELIOS_RISTORANTE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.FAMILY, Location.DOWNTOWN),
	FERRETTI_RISTORANTE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.FAMILY, Location.NORTH_SIDE),
	FINDI(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.FAMILY, Location.EAST_SIDE),
	FINZI_1(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.FAMILY, Location.WEST_SIDE),
	FOGGIA_RISTORANTE(Cuisine.ITALIAN, Cost.CHEAP, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	GIOVANYS_RISTORANTE(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.DOWNTOWN),
	IL_CARPACCIO(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	IL_COCCODRILLO(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.EAST_SIDE),
	IL_GUSTA_PASTA(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.WEST_SIDE),
	IL_PINOCCHIO(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	IL_RISTORANTE(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.DOWNTOWN),
	IL_TRANELLO(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.NORTH_SIDE),
	ITALIA_PIZZA(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.EAST_SIDE),
	ITALIA_TRATTORIA(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.WEST_SIDE),
	ITALIAN_CAFE(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	ITALIANS_CAFE(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	CONTINI(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	L_GARBINO(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	LESTERINA(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	VISCONTI(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	LES_SERENADES(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.DOWNTOWN),
	MANCINI(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	PASTARITO(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.EAST_SIDE),
	MILANO(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.WEST_SIDE),
	PASTAPPETIT(Cuisine.ITALIAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	AKI(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.DOWNTOWN),
	EBIS(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	EDOKKO(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.EAST_SIDE),
	FOUJITA(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.WEST_SIDE),
	SUSHI_PLACE(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	KILALA(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.DOWNTOWN),
	KINUGAWA(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.NORTH_SIDE),
	KOESTU(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.EAST_SIDE),
	MATSUDA(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.WEST_SIDE),
	SAKURA(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	MIDORY(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	NARITAKE(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	NODAIWA(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	SANUKIA(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	SAPPORO(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	YASUBE(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.DOWNTOWN),
	YAKINIKU(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	AI(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.EAST_SIDE),
	HOKKAIDO(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.WEST_SIDE),
	TOKYO(Cuisine.JAPANESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	AKITA(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.LIVELY, Location.DOWNTOWN),
	BIZAN(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.LIVELY, Location.NORTH_SIDE),
	JUJI(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.LIVELY, Location.EAST_SIDE),
	KINTARO(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.LIVELY, Location.WEST_SIDE),
	KOFUKU(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	KOBA(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.QUIET, Location.DOWNTOWN),
	OKINAWA(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.QUIET, Location.NORTH_SIDE),
	RAMEN_PLACE(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.QUIET, Location.EAST_SIDE),
	SUSHI_WASABI(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.QUIET, Location.WEST_SIDE),
	SAP(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.QUIET, Location.SOUTH_SIDE),
	YOKOSUNA(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	TAKEO(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	ICHO(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	KICCHO(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	SUN(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	AKIDA(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.FAMILY, Location.DOWNTOWN),
	INAGIKU(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.FAMILY, Location.NORTH_SIDE),
	MATSUYA(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.FAMILY, Location.EAST_SIDE),
	MAKI_CORNER(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.FAMILY, Location.WEST_SIDE),
	SUSHIKO(Cuisine.JAPANESE, Cost.CHEAP, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	KASUMI(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.DOWNTOWN),
	SAMURA(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	SAYUKI(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.EAST_SIDE),
	YASAMI(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.WEST_SIDE),
	AZABU(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	JAPOTORI(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.DOWNTOWN),
	JAPORAMA(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.NORTH_SIDE),
	MATSUDO(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.EAST_SIDE),
	NIPON(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.WEST_SIDE),
	NIPONYAKI(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	YEN(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	TSUKIZI(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	YOOKOSO(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	AKITO(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	YYOTAN(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	KONOHAWA(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.DOWNTOWN),
	MIKADO(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	SUCHIKU(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.EAST_SIDE),
	BARAMAKI(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.WEST_SIDE),
	HUTARU(Cuisine.JAPANESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	AYCA(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.DOWNTOWN),
	ABA_TURKISH(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	A_LA_TURKA(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.EAST_SIDE),
	AGORA(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.WEST_SIDE),
	AKDENIZ(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	ALI_BABA_OF_WEST_SIDE(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.DOWNTOWN),
	ANATOLIA(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.NORTH_SIDE),
	GYRO(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.EAST_SIDE),
	ANATOLYA_CORNER(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.WEST_SIDE),
	ANTALIA_MED(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	ANTIQUE_GARAGE(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	AYZA_WINE(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	BABIJI(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	BABYLON_HOOKAH_LOUNGE(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	BARAK(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	BELLA_LUNA(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.DOWNTOWN),
	BEREKET(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	BODRUM(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.EAST_SIDE),
	CAPPADOCE(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.WEST_SIDE),
	CAUCASUS_GARDEN(Cuisine.TURKISH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	DERVISH(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.LIVELY, Location.DOWNTOWN),
	DERYA(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.LIVELY, Location.NORTH_SIDE),
	DROM(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.LIVELY, Location.EAST_SIDE),
	EFENDI(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.LIVELY, Location.WEST_SIDE),
	EFES(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	EKIN(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.QUIET, Location.DOWNTOWN),
	ELLA(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.QUIET, Location.NORTH_SIDE),
	FEZ(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.QUIET, Location.EAST_SIDE),
	GULLUOGLU_BAKLAVA(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.QUIET, Location.WEST_SIDE),
	HANCI(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.QUIET, Location.SOUTH_SIDE),
	HORUS(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	HAZAR(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	ISHTAR(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	IZNIK(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	KAZAN(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	KEBAB_HOUSE_II(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.FAMILY, Location.DOWNTOWN),
	KIBELLE(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.FAMILY, Location.NORTH_SIDE),
	KOKOREC(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.FAMILY, Location.EAST_SIDE),
	KUZU_KITCHEN(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.FAMILY, Location.WEST_SIDE),
	LIMON(Cuisine.TURKISH, Cost.CHEAP, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	MEKAN(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.DOWNTOWN),
	MMM_ENFES(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	PERA_SOHO(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.EAST_SIDE),
	PESCATORE(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.WEST_SIDE),
	ROKA(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	SARASTRO(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.DOWNTOWN),
	SAVANN(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.NORTH_SIDE),
	SIMITSMITH(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.EAST_SIDE),
	SIZIN(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.WEST_SIDE),
	SMYRNA_(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	TAKSIM_SQUARE(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	TARABIA(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	TAS_PIDE(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	THE_COUNTRY_KEBAB(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	TROY_GRILL(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	TURKISS(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.DOWNTOWN),
	TURKSFROGS(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	TURKUAZ(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.EAST_SIDE),
	USKUDAR(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.WEST_SIDE),
	SULTAN(Cuisine.TURKISH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	ASIA_PARFUM(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.DOWNTOWN),
	ANCIAN_DRAGON(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	ASIA_PLACE(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.EAST_SIDE),
	ASIA_STAR(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.WEST_SIDE),
	BEIJING(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	CHIENG_MAI(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.DOWNTOWN),
	CHIM(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.NORTH_SIDE),
	CHINA_CLUB(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.EAST_SIDE),
	CHINA_EXPRESS(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.WEST_SIDE),
	CHINA_STAR(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	CHINESE_WALL_(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	CHO_GAO(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	DAI_DUONG(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	DONG(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	DRAGON(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	ESCADE_CHINE(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.DOWNTOWN),
	ETOIDE_CHINE(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	GOLD_DRAGON(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.EAST_SIDE),
	HAO_HAO(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.WEST_SIDE),
	HENG_LAY(Cuisine.CHINESE, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	JADE(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.LIVELY, Location.DOWNTOWN),
	JILIYA(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.LIVELY, Location.NORTH_SIDE),
	JUJUBE(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.LIVELY, Location.EAST_SIDE),
	KANCI(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.LIVELY, Location.WEST_SIDE),
	KAWLOON(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	KINGA(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.QUIET, Location.DOWNTOWN),
	IMPERIAL_DRAGON(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.QUIET, Location.NORTH_SIDE),
	LAC_DE_CHINE(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.QUIET, Location.EAST_SIDE),
	SAIGON(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.QUIET, Location.WEST_SIDE),
	SHANGHAI(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.QUIET, Location.SOUTH_SIDE),
	LIDO(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	LIN(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	LION_(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	LOTUS_FLOWER(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	TAOKAN(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	MANDARIN(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.FAMILY, Location.DOWNTOWN),
	MEYLIWA(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.FAMILY, Location.NORTH_SIDE),
	MIZUSHI(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.FAMILY, Location.EAST_SIDE),
	MONGOLIAN(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.FAMILY, Location.WEST_SIDE),
	NEW_EMPIRE(Cuisine.CHINESE, Cost.CHEAP, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	PEKIN_EXPRESS(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.DOWNTOWN),
	NEW_FULI(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	NOODKING(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.EAST_SIDE),
	OASIS_(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.WEST_SIDE),
	PEKIN(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	PHENIX_(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.DOWNTOWN),
	PHOU_KHET(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.NORTH_SIDE),
	PHU_DO(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.EAST_SIDE),
	SAIGONKUN(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.WEST_SIDE),
	ROYAL_ORCHID(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	SATSUKI(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	SHAN_GOUT(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	SHANGAI_PALACE(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	SOCTRANG(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	SONG_HOAT(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	TOKU(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.DOWNTOWN),
	TSOU(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	VONG(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.EAST_SIDE),
	YANG(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.WEST_SIDE),
	YONG(Cuisine.CHINESE, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	MOULIN2(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.DOWNTOWN),
	LORANGERIE_DU_CHATEAU(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	COUTURE(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.EAST_SIDE),
	PAPILLON(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.WEST_SIDE),
	MARINE(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	LETAPE(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.DOWNTOWN),
	COURONNE(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.NORTH_SIDE),
	GLYCINES(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.EAST_SIDE),
	ADELITA(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.WEST_SIDE),
	TRIPOT(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	PASHA(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	GENTILLIERE(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	ROSERAIE(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	BOUDOR(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	PLATANES(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	OLIVIERS(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.DOWNTOWN),
	AU_BON_VIVANT(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	FLEURAY(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.EAST_SIDE),
	POIDRAS_THIERRY(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.WEST_SIDE),
	ANATOLIAN_GYRO(Cuisine.FRENCH, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	CAILLERE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.LIVELY, Location.DOWNTOWN),
	ARPEGE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.LIVELY, Location.NORTH_SIDE),
	PATISSON(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.LIVELY, Location.EAST_SIDE),
	CHATEAU_BELLEVUE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.LIVELY, Location.WEST_SIDE),
	VAL_DE_SAVE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	ELDORADO(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.QUIET, Location.DOWNTOWN),
	GRANDE_TOUR(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.QUIET, Location.NORTH_SIDE),
	PAVILLON_LIMERE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.QUIET, Location.EAST_SIDE),
	RESTAURANT(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.QUIET, Location.WEST_SIDE),
	EN_BONNE_COMPAGNIE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.QUIET, Location.SOUTH_SIDE),
	LION_DOR(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	PARIS_BISTRO(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	OCEANIS(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	DELYSE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	AMARANTE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	VAL_DAMBY(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.FAMILY, Location.DOWNTOWN),
	COCAGNOU(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.FAMILY, Location.NORTH_SIDE),
	DEUVALIERE(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.FAMILY, Location.EAST_SIDE),
	LODEON(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.FAMILY, Location.WEST_SIDE),
	MISTRAL(Cuisine.FRENCH, Cost.CHEAP, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	TILLEULS(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.DOWNTOWN),
	VOIDOR(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	TRAIT_DUNION(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.EAST_SIDE),
	CERDAGNE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.WEST_SIDE),
	GRANGE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	MAISON_BLANCHE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.DOWNTOWN),
	MOULIN_DE_PLANCHE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.NORTH_SIDE),
	SAINT_HONORE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.EAST_SIDE),
	CHATEAU_DE_BOUESSE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.WEST_SIDE),
	LOREE_DE_CHAMBORD(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	TAJ_MAHAL(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	LOREE_DU_BOIS(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	BELSAISONS(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	CHATEAU_DE_BAGNOLS(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	COCINA_MUNDI(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	PETIT_BONNEVAL(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.DOWNTOWN),
	CASINO_DE_ROYAT(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	CHATEAU_DE_VERIE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.EAST_SIDE),
	CHEZ_FELIX(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.WEST_SIDE),
	MONSTRE(Cuisine.FRENCH, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	ARRIBA_MEXICO(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.DOWNTOWN),
	ATLANTIC_OAK(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	AY_MEXICO(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.EAST_SIDE),
	AZTECA(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.WEST_SIDE),
	BOCAMEXA(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	CADILLAC(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.DOWNTOWN),
	CANDELARIA(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.NORTH_SIDE),
	CHARLYS(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.EAST_SIDE),
	CHARLYS_TEX_MEX(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.WEST_SIDE),
	CHIPOTLE(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	KRISTINA(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	MARTI(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	CHICANOS(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	CHICA_TEX_MEX(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	CHIDOS2(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	DONA(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.DOWNTOWN),
	EAGLES_DEN_TEX_MEX(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	ELBURRITO_MEXICANO(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.EAST_SIDE),
	ELCAMINO_DELSOL(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.WEST_SIDE),
	ELMEXICANO(Cuisine.MEXICAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	ELPOPOCA(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.LIVELY, Location.DOWNTOWN),
	ELSOMBRERO(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.LIVELY, Location.NORTH_SIDE),
	ELPEDRO(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.LIVELY, Location.EAST_SIDE),
	ELNOPAL(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.LIVELY, Location.WEST_SIDE),
	ELRANCHO(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	HOLLYWOOD_CAFE(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.QUIET, Location.DOWNTOWN),
	HOUSTON_TEX_MEX(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.QUIET, Location.NORTH_SIDE),
	ELCANTINA_MEXICAINE(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.QUIET, Location.EAST_SIDE),
	MEXICANA(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.QUIET, Location.WEST_SIDE),
	PARRILLA(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.QUIET, Location.SOUTH_SIDE),
	ELJOHNS(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	ELMEXICO(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	ELSHIP_TEX_MEX(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	ELTAMPICO_TEX_MEX(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	ELTEX_MEX(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	LOS_MEXICANOS(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.FAMILY, Location.DOWNTOWN),
	LUNA(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.FAMILY, Location.NORTH_SIDE),
	MEXI_AND_CO(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.FAMILY, Location.EAST_SIDE),
	MEXICANO(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.FAMILY, Location.WEST_SIDE),
	MEXICANOS(Cuisine.MEXICAN, Cost.CHEAP, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	MEXICO_CITY(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.DOWNTOWN),
	MEXICO_LINDO(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	MEXICO_LOCO(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.EAST_SIDE),
	MEXICO_MAGICO(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.WEST_SIDE),
	MEXICOR(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	MUCHO_MEX(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.DOWNTOWN),
	O_MEXICO(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.NORTH_SIDE),
	OTACOS(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.EAST_SIDE),
	PAPPASITOS(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.WEST_SIDE),
	RANCH_RIVER(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	SOLOTEX_MEX(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	TACOMEX(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	TEX_MEX(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	ELPACHUCA(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	ELROSARIO(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	MEX_SOUTH(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.DOWNTOWN),
	TEXAS_CITY(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	THE_WESTERNER_TEX_MEX(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.EAST_SIDE),
	TRADING_POST_TEX_MEX(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.WEST_SIDE),
	VIVA_MEXICO(Cuisine.MEXICAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	AGUJJIM(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.DOWNTOWN),
	AHSI(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	ANJU(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.EAST_SIDE),
	BADA(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.WEST_SIDE),
	BALWOO_GONGYANG(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	BINGSU(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.DOWNTOWN),
	BOBEA(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.NORTH_SIDE),
	BONG(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.EAST_SIDE),
	BOSSAM(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.WEST_SIDE),
	BULGOGI(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	DOENJANG(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	DOTORIMUK(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	DUBUKIMCHI(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	EDA(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	GALBI(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	GAON(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.DOWNTOWN),
	GARI(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	GAYA(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.EAST_SIDE),
	GOPCHANG(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.WEST_SIDE),
	GUIBINE(Cuisine.KOREAN, Cost.EXPENSIVE, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	GYERANJJIM(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.LIVELY, Location.DOWNTOWN),
	HAEMUL_PAJEON(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.LIVELY, Location.NORTH_SIDE),
	HANGLI(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.LIVELY, Location.EAST_SIDE),
	HANLIM(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.LIVELY, Location.WEST_SIDE),
	HANSUNG(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	HOBAKJUK(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.QUIET, Location.DOWNTOWN),
	JANTCHI(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.QUIET, Location.NORTH_SIDE),
	JAPCHAE(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.QUIET, Location.EAST_SIDE),
	JJAMBBONG(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.QUIET, Location.WEST_SIDE),
	JULES(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.QUIET, Location.SOUTH_SIDE),
	KALGUKSU(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	KONGGUKSU(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	KOOKIL_KWAN(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	KOREAN_BARBECUE(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	KOREDAM(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	LA_YEON(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.FAMILY, Location.DOWNTOWN),
	LAB(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.FAMILY, Location.NORTH_SIDE),
	LITTSEOU(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.FAMILY, Location.EAST_SIDE),
	MATSUBICHI(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.FAMILY, Location.WEST_SIDE),
	MIDAM(Cuisine.KOREAN, Cost.CHEAP, Atmosphere.FAMILY, Location.SOUTH_SIDE),
	MUDFISH(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.DOWNTOWN),
	NABI(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.NORTH_SIDE),
	NAENGMYEON(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.EAST_SIDE),
	NAMOU(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.WEST_SIDE),
	ODORI(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.LIVELY, Location.SOUTH_SIDE),
	PPEONGTWIGI(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.DOWNTOWN),
	SAMGYETANG(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.NORTH_SIDE),
	SAMO(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.EAST_SIDE),
	SEOUL(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.WEST_SIDE),
	SHIM(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.QUIET, Location.SOUTH_SIDE),
	SIKZACK(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.DOWNTOWN),
	SOBANE(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.NORTH_SIDE),
	SOON(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.EAST_SIDE),
	SOURA(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.WEST_SIDE),
	SUNDAE(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.ROMANTIC, Location.SOUTH_SIDE),
	WABOSSO(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.DOWNTOWN),
	WOO_JUNG(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.NORTH_SIDE),
	MATSUBA(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.EAST_SIDE),
	DOLAJI(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.WEST_SIDE),
	GINMIN(Cuisine.KOREAN, Cost.AFFORDABLE, Atmosphere.FAMILY, Location.SOUTH_SIDE);
///	
	public final Cuisine cuisine;
	public final Cost cost;
	public final Atmosphere ambiance;
	public final Location district;
	@SuppressWarnings("serial")
	private static final List<Class<? extends Criterion>> CRITERIA = new ArrayList<Class<? extends Criterion>> () {{ add(Cost.class); add(Cuisine.class); add(Atmosphere.class); add(Location.class); }};
	
	Restaurant (Cuisine cuisine, Cost cost, Atmosphere ambiance, Location district) {
		this.cuisine = cuisine;
		this.cost = cost;
		this.ambiance = ambiance;
		this.district = district;
	}

	@Override
	public Criterion getValue (Class<? extends Criterion> c) {
		return c == Cuisine.class ? cuisine :
			c == Cost.class ? cost : c == Atmosphere.class? ambiance : c == Location.class ? district :null; // throw error? 
	}

	@Override
	public List<Class<? extends Criterion>> getCriteria() {

		return CRITERIA;
	}

	public String capitalize(String input){
		input = input.replace("_", " ");
		String output = input.substring(0, 1).toUpperCase() + input.substring(1).toLowerCase();
		return output;

	}
	
	public String print(){
		  return "It's a "+ this.ambiance+", " +this.cost+" "+ this.cuisine+ " restaurant on the " + this.district;
	}

	@Override
	public String getFrVersion() {
		// TODO Auto-generated method stub
		return  this.toString();
	}

	@Override
	public String toString(){
		return this.capitalize(this.name());
	}

}
