strips_preconditions(a81,[p1]).
strips_achieves(a81,p4).
strips_preconditions(a82,[p4]).
strips_preconditions(a71,[p1]).
strips_achieves(a71,p5).
strips_preconditions(a72,[p5]).
strips_achieves(a91,p6).
strips_preconditions(a92,[p6]).
strips_achieves(a92,p2).
strips_achieves(a102,p2).
strips_preconditions(a21,[p1]).
strips_achieves(a22,p8).
strips_preconditions(a31,[p1]).
strips_achieves(a31,p10).
strips_preconditions(a32,[p10]).
strips_achieves(a32,p8).
strips_preconditions(a41,[p8]).
strips_achieves(a41,p11).
strips_preconditions(a42,[p11]).
strips_achieves(a42,p2).
strips_preconditions(a51,[p8]).
strips_achieves(a51,p12).
strips_preconditions(a52,[p12]).
strips_achieves(a52,p2).
strips_achieves(r8,cr8).
strips_primitive(r8).
strips_achieves(r7,cr7).
strips_primitive(r7).
strips_achieves(r9,cr9).
strips_primitive(r9).
strips_achieves(r10,cr10).
strips_primitive(r10).
strips_achieves(r2,cr2).
strips_primitive(r2).
strips_achieves(r3,cr3).
strips_primitive(r3).
strips_achieves(r4,cr4).
strips_primitive(r4).
strips_achieves(r1,cr1).
strips_primitive(r1).
strips_primitive(p5).
strips_primitive(cr3).
strips_primitive(cr1).
strips_primitive(p10).
strips_primitive(p2).
strips_primitive(p12).
strips_primitive(cr9).
strips_primitive(p4).
strips_primitive(p11).
strips_primitive(cr4).
strips_primitive(cr8).
strips_primitive(cr7).
strips_primitive(p8).
strips_primitive(p6).
strips_primitive(cr2).
strips_primitive(p1).
strips_primitive(cr10).
strips_achieves(a81,p4).
strips_preconditions(a82,[p4]).
strips_achieves(a91,p6).
strips_preconditions(a92,[p6]).
strips_achieves(a92,p2).
strips_achieves(a102,p2).
strips_achieves(a21,p9).
strips_preconditions(a22,[p9]).
strips_achieves(a22,p8).
strips_achieves(a31,p10).
strips_preconditions(a32,[p10]).
strips_achieves(a32,p8).
strips_preconditions(a41,[p8]).
strips_achieves(a41,p11).
strips_preconditions(a42,[p11]).
strips_achieves(a42,p2).
strips_preconditions(a51,[p8]).
strips_achieves(a51,p12).
strips_preconditions(a52,[p12]).
strips_achieves(a52,p2).
strips_achieves(r8,cr8).
strips_primitive(r8).
strips_achieves(r7,cr7).
strips_primitive(r7).
strips_achieves(r9,cr9).
strips_primitive(r9).
strips_achieves(r10,cr10).
strips_primitive(r10).
strips_achieves(r2,cr2).
strips_primitive(r2).
strips_achieves(r3,cr3).
strips_primitive(r3).
strips_achieves(r4,cr4).
strips_primitive(r4).
strips_achieves(r5,cr5).
strips_primitive(r5).
strips_achieves(r1,cr1).
strips_primitive(r1).
strips_primitive(p2).
strips_primitive(p6).
strips_primitive(cr4).
strips_primitive(cr5).
strips_primitive(cr8).
strips_primitive(cr1).
strips_primitive(p10).
strips_primitive(cr10).
strips_primitive(cr9).
strips_primitive(p12).
strips_primitive(p4).
strips_primitive(cr3).
strips_primitive(p9).
strips_primitive(p8).
strips_primitive(cr2).
strips_primitive(cr7).
strips_primitive(p11).
strips_preconditions(a81,[p1]).strips_achieves(a81,p4).
strips_preconditions(a82,[p4]).strips_achieves(a82,p3).
strips_preconditions(a71,[p1]).strips_achieves(a71,p5).
strips_preconditions(a72,[p5]).strips_achieves(a72,p3).
strips_preconditions(a91,[p3]).
strips_achieves(a92,p2).
strips_preconditions(a101,[p3]).strips_achieves(a101,p7).
strips_preconditions(a102,[p7]).strips_achieves(a102,p2).
strips_preconditions(a21,[p1]).strips_achieves(a21,p9).
strips_preconditions(a22,[p9]).strips_achieves(a22,p8).
strips_preconditions(a31,[p1]).strips_achieves(a31,p10).
strips_preconditions(a32,[p10]).strips_achieves(a32,p8).
strips_preconditions(a41,[p8]).strips_achieves(a41,p11).
strips_preconditions(a42,[p11]).strips_achieves(a42,p2).
strips_preconditions(a51,[p8]).strips_achieves(a51,p12).
strips_preconditions(a52,[p12]).strips_achieves(a52,p2).
strips_achieves(r8,cr8).
strips_primitive(r8).strips_achieves(r9,cr9).
strips_primitive(r9).strips_achieves(r10,cr10).
strips_primitive(r10).strips_achieves(r2,cr2).
strips_primitive(r2).strips_achieves(r4,cr4).
strips_primitive(r4).strips_achieves(r1,cr1).
strips_primitive(r1).strips_primitive(p5).
strips_primitive(p4).
strips_primitive(cr9).
strips_primitive(cr2).
strips_primitive(p9).
strips_primitive(p12).
strips_primitive(p10).
strips_primitive(p11).
strips_primitive(p2).
strips_primitive(p3).
strips_primitive(cr8).
strips_primitive(p7).
strips_primitive(cr1).
strips_primitive(cr4).
strips_primitive(cr10).
strips_primitive(p8).
strips_primitive(p1).
strips_preconditions(a81,[p1]).strips_achieves(a81,p4).
strips_preconditions(a82,[p4]).strips_achieves(a82,p3).
strips_preconditions(a71,[p1]).strips_achieves(a71,p5).
strips_preconditions(a72,[p5]).strips_achieves(a72,p3).
strips_preconditions(a91,[p3]).strips_achieves(a91,p6).
strips_preconditions(a92,[p6]).strips_achieves(a92,p2).
strips_preconditions(a101,[p3]).strips_achieves(a101,p7).
strips_preconditions(a102,[p7]).strips_achieves(a102,p2).
strips_preconditions(a21,[p1]).strips_achieves(a21,p9).
strips_preconditions(a22,[p9]).strips_achieves(a22,p8).
strips_preconditions(a31,[p1]).
strips_achieves(a32,p8).
strips_preconditions(a41,[p8]).strips_achieves(a41,p11).
strips_preconditions(a42,[p11]).strips_achieves(a42,p2).
strips_preconditions(a51,[p8]).
strips_achieves(a52,p2).
strips_achieves(r8,cr8).
strips_primitive(r8).
strips_achieves(r9,cr9).
strips_primitive(r9).
strips_achieves(r10,cr10).
strips_primitive(r10).
strips_achieves(r6,cr6).
strips_primitive(r6).
strips_achieves(r3,cr3).
strips_primitive(r3).
strips_achieves(r4,cr4).
strips_primitive(r4).
strips_achieves(r1,cr1).
strips_primitive(r1).
strips_primitive(p3).
strips_primitive(p6).
strips_primitive(cr3).
strips_primitive(p7).
strips_primitive(cr1).
strips_primitive(p8).
strips_primitive(p4).
strips_primitive(cr10).
strips_primitive(p2).
strips_primitive(cr6).
strips_primitive(p1).
strips_primitive(cr9).
strips_primitive(p11).
strips_primitive(p5).
strips_primitive(p9).
strips_primitive(cr4).
strips_primitive(cr8).
strips_preconditions(a81,[p1]).strips_achieves(a81,p4).
strips_preconditions(a82,[p4]).strips_achieves(a82,p3).
strips_preconditions(a71,[p1]).strips_achieves(a71,p5).
strips_preconditions(a72,[p5]).strips_achieves(a72,p3).
strips_preconditions(a91,[p3]).strips_achieves(a91,p6).
strips_preconditions(a92,[p6]).
strips_preconditions(a101,[p3]).strips_achieves(a101,p7).
strips_preconditions(a102,[p7]).
strips_preconditions(a21,[p1]).strips_achieves(a21,p9).
strips_preconditions(a22,[p9]).
strips_preconditions(a31,[p1]).strips_achieves(a31,p10).
strips_preconditions(a32,[p10]).
strips_achieves(a41,p11).
strips_preconditions(a42,[p11]).


strips_achieves(r8,cr8).
strips_primitive(r8).
strips_achieves(r7,cr7).
strips_primitive(r7).
strips_achieves(r10,cr10).
strips_primitive(r10).
strips_achieves(r6,cr6).
strips_primitive(r6).
strips_achieves(r2,cr2).
strips_primitive(r2).
strips_achieves(r3,cr3).
strips_primitive(r3).
strips_achieves(r5,cr5).
strips_primitive(r5).
strips_achieves(r1,cr1).
strips_primitive(r1).
strips_primitive(cr10).
strips_primitive(cr2).
strips_primitive(cr5).
strips_primitive(cr7).
strips_primitive(p11).
strips_primitive(p3).
strips_primitive(p9).
strips_primitive(cr8).
strips_primitive(p5).
strips_primitive(cr3).
strips_primitive(p1).
strips_primitive(p7).
strips_primitive(p4).
strips_primitive(cr1).
strips_primitive(p6).
strips_primitive(p10).
strips_primitive(cr6).
strips_achieves(jgjgiojigojriogjifgjkfbknnnpdfihnfjhg).
texte à insérer à la fin du fichiertexte à insérer à la fin du fichier
texte à insérer à la fin du fichier